In [1]:
import torch

In [3]:
def describe(x):
    print("타입: {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))

In [4]:
describe(torch.Tensor(2, 3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[2.5715e-38, 1.0286e-37, 2.7186e-38],
        [2.5581e-35, 4.1144e-37, 3.8797e-37]])


In [6]:
describe(torch.rand(2,3))  # 균등분포
describe(torch.randn(2,3))  # 표준 정규분포

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.9516, 0.7156, 0.6564],
        [0.0196, 0.3413, 0.4476]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 1.1615,  0.4323, -0.3738],
        [ 1.0184, -0.8679,  0.6235]])


In [8]:
describe(torch.zeros(2,3))
describe(torch.ones(2,3))
describe(torch.ones(2,3).fill_(5))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [9]:
x = torch.Tensor([[1,2,3],[4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
x = torch.randn(2,3)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.9141,  0.2717,  1.1248],
        [-0.3317,  0.0375,  1.1302]])


In [11]:
torch.add(x,x)

tensor([[ 1.8282,  0.5433,  2.2495],
        [-0.6634,  0.0750,  2.2604]])

In [12]:
x + x

tensor([[ 1.8282,  0.5433,  2.2495],
        [-0.6634,  0.0750,  2.2604]])

In [14]:
x = torch.arange(6)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])


In [15]:
x = x.view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [16]:
describe(torch.sum(x, dim=0))

타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([3, 5, 7])


In [17]:
describe(torch.sum(x, dim=1))

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 3, 12])


In [18]:
describe(torch.transpose(x, 0, 1))  # 두번째와 세번째 매개변수로 전달된 차원을 전치한 텐서를 만들어줌

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [19]:
x = torch.arange(6).view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [20]:
indices = torch.LongTensor([0,2])

In [21]:
indices

tensor([0, 2])

In [22]:
describe(torch.index_select(x, dim=1, index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])


In [23]:
indices = torch.LongTensor([0,0])
describe(torch.index_select(x, dim=0, index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [24]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])

In [25]:
row_indices

tensor([0, 1])

In [26]:
col_indices

tensor([0, 1])

In [27]:
describe(x[row_indices, col_indices])

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([0, 4])


In [30]:
x[[0,1]]

tensor([[0, 1, 2],
        [3, 4, 5]])

In [35]:
x[:, [0,1]]

tensor([[0, 1],
        [3, 4]])

In [36]:
describe(torch.cat([x,x],dim=0))

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [37]:
describe(torch.cat([x,x],dim=1))

타입: torch.LongTensor
크기: torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [38]:
describe(torch.stack([x,x]))

타입: torch.LongTensor
크기: torch.Size([2, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [39]:
x2 = torch.ones(3,2)
x2[:,1] += 1
describe(x2)

타입: torch.FloatTensor
크기: torch.Size([3, 2])
값: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [45]:
x1 = torch.arange(6).view(2,3).float()

In [46]:
x1.type()

'torch.FloatTensor'

In [47]:
describe(torch.mm(x1, x2))

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[ 3.,  6.],
        [12., 24.]])


In [48]:
x = torch.ones(2,2,requires_grad=True)
describe(x)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [49]:
print(torch.cuda.is_available())

False


## 1.5 연습문제

In [2]:
# pyTorch dimension에 대한 이해 - 참고: https://towardsdatascience.com/understanding-dimensions-in-pytorch-6edf9972d3be

In [8]:
# 1. 2D 텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가하세요.
x = torch.randn(2,3)
x

tensor([[ 1.2488, -0.9781,  0.8232],
        [ 1.5018,  0.6772, -0.2954]])

In [7]:
x = torch.unsqueeze(x, 0)
x

tensor([[[-0.9835,  0.1909, -0.7434],
         [-0.8819,  1.3089,  0.0804]]])

In [9]:
# 2. 이전 텐서에 추가한 차원을 삭제하세요.
x = torch.squeeze(x, 0)
x

tensor([[ 0.4688,  0.9051,  1.3427],
        [-0.8017, -2.0337, -0.4360]])

In [10]:
# 3. 범위가 [3,7)이고 크기가 5*3인 랜덤한 텐서를 만드세요.
M = 8
m = 4
#create tensor with random values in range (min, max)
x = (M - m)*torch.rand((5, 3)) + m
x

tensor([[4.0991, 7.9627, 6.4734],
        [7.8015, 7.3371, 6.3551],
        [5.4962, 6.8322, 5.0916],
        [4.4837, 7.1988, 4.5929],
        [5.3344, 7.9497, 4.5429]])

In [11]:
# 4. 정규분포를 사용해 텐서를 만드세요.
x = torch.randn(2, 3)
x

tensor([[ 1.4187, -0.6665,  0.4704],
        [-0.3148,  0.2254, -0.0907]])

In [20]:
x = torch.rand(2,3)
x.normal_()

tensor([[ 0.9819, -0.4371,  1.1632],
        [ 1.4386,  1.5669,  0.3594]])

In [16]:
# 5. 텐서 torch.Tensor([1,1,1,0,1])에서 0이 아닌 원소의 인덱스를 추출하세요.
x = torch.Tensor([1,1,1,0,1])
x.nonzero()

tensor([[0],
        [1],
        [2],
        [4]])

In [17]:
(x != 0).nonzero()

tensor([[0],
        [1],
        [2],
        [4]])

In [12]:
# 6. 크기가 (3,1)인 랜덤한 텐서를 만들고 네 벌을 복사해 쌓으세요.
x = torch.rand((3, 1))
x = torch.stack([x]*4, 0)
x

tensor([[[0.1408],
         [0.6785],
         [0.6254]],

        [[0.1408],
         [0.6785],
         [0.6254]],

        [[0.1408],
         [0.6785],
         [0.6254]],

        [[0.1408],
         [0.6785],
         [0.6254]]])

In [21]:
x = torch.rand(3, 1)
x.expand(3, 4)

tensor([[0.3295, 0.3295, 0.3295, 0.3295],
        [0.3608, 0.3608, 0.3608, 0.3608],
        [0.5789, 0.5789, 0.5789, 0.5789]])

In [23]:
# 7. 2차원 행렬 두 개 (a=torch.rand(3,4,5), b=torch.rand(3,5,4))의 배치 행렬 곱셈을 계산하세요.
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
res = torch.bmm(a, b)
res

tensor([[[1.3906, 1.9315, 1.5575, 1.1526],
         [2.0519, 1.4531, 1.7263, 0.8069],
         [1.4484, 1.3829, 1.6504, 0.9801],
         [2.5863, 2.4270, 2.7142, 1.4527]],

        [[0.8904, 1.2216, 0.8538, 1.2778],
         [1.2734, 1.7087, 1.4265, 1.7703],
         [1.2523, 1.9375, 1.6872, 1.8705],
         [0.4553, 0.9144, 0.7678, 0.7535]],

        [[0.6112, 0.3331, 1.4809, 0.9852],
         [1.0773, 0.8675, 2.0324, 1.7035],
         [1.0813, 0.9587, 2.1500, 1.7063],
         [1.0993, 1.7213, 2.4321, 1.7480]]])

In [26]:
# 8. 3차원 행렬 (a=torch.rand(3,4,5))과 2차원 행렬 (b=torch.rand(5,4))의 배치 행렬 곱셈을 계산하세요.
a = torch.rand(3,4,5)
b = torch.rand(5,4)
res = torch.matmul(a, b)
res

tensor([[[1.3652, 1.0599, 1.1380, 0.8087],
         [1.7318, 0.8234, 1.6781, 1.6140],
         [0.9132, 0.6925, 1.1813, 0.7703],
         [1.4187, 0.8187, 1.2971, 1.0243]],

        [[1.7588, 1.1413, 1.4127, 0.7713],
         [1.2041, 0.7323, 1.3086, 1.3736],
         [1.6636, 1.5186, 2.2179, 1.7150],
         [1.4576, 1.1128, 1.4608, 0.9451]],

        [[1.7739, 1.3062, 1.8004, 1.0411],
         [1.2061, 1.2641, 1.8013, 1.1699],
         [1.4993, 1.2126, 1.6730, 1.3353],
         [1.8697, 1.2619, 1.9439, 1.5888]]])

In [13]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
res = torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))
res

tensor([[[1.7256, 1.0742, 1.6607, 1.9475],
         [0.8587, 0.7538, 1.1936, 1.2303],
         [1.7655, 1.5670, 2.2563, 1.6165],
         [0.6104, 0.7239, 1.0427, 0.7171]],

        [[0.3094, 0.4853, 0.6300, 0.3329],
         [1.1839, 1.0185, 1.2982, 1.1875],
         [1.4582, 1.3001, 1.7810, 1.3763],
         [1.2042, 1.0789, 1.5162, 1.2835]],

        [[0.3071, 0.3185, 0.4788, 0.3478],
         [1.4211, 1.1516, 1.5224, 1.4276],
         [0.3865, 0.7203, 0.9040, 0.3751],
         [0.7061, 0.5700, 0.8413, 0.7610]]])

In [14]:
b.size()

torch.Size([5, 4])

In [ ]:
# The asterisk (*) can be used in python to unpack a list into its individual elements, thus passing to view the correct form of input arguments it expects.