In [3]:
def describe(x):
    print("타입: {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))

In [4]:
import torch
describe(torch.Tensor(2, 3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[2.5715e-38, 1.0286e-37, 2.7186e-38],
        [2.5581e-35, 4.1144e-37, 3.8797e-37]])


In [6]:
describe(torch.rand(2,3))  # 균등분포
describe(torch.randn(2,3))  # 표준 정규분포

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.9516, 0.7156, 0.6564],
        [0.0196, 0.3413, 0.4476]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 1.1615,  0.4323, -0.3738],
        [ 1.0184, -0.8679,  0.6235]])


In [8]:
describe(torch.zeros(2,3))
describe(torch.ones(2,3))
describe(torch.ones(2,3).fill_(5))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [9]:
x = torch.Tensor([[1,2,3],[4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
x = torch.randn(2,3)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[ 0.9141,  0.2717,  1.1248],
        [-0.3317,  0.0375,  1.1302]])


In [11]:
torch.add(x,x)

tensor([[ 1.8282,  0.5433,  2.2495],
        [-0.6634,  0.0750,  2.2604]])

In [12]:
x + x

tensor([[ 1.8282,  0.5433,  2.2495],
        [-0.6634,  0.0750,  2.2604]])

In [14]:
x = torch.arange(6)
describe(x)

타입: torch.LongTensor
크기: torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])


In [15]:
x = x.view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [16]:
describe(torch.sum(x, dim=0))

타입: torch.LongTensor
크기: torch.Size([3])
값: 
tensor([3, 5, 7])


In [17]:
describe(torch.sum(x, dim=1))

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([ 3, 12])


In [18]:
describe(torch.transpose(x, 0, 1))  # 두번째와 세번째 매개변수로 전달된 차원을 전치한 텐서를 만들어줌

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [19]:
x = torch.arange(6).view(2,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [20]:
indices = torch.LongTensor([0,2])

In [21]:
indices

tensor([0, 2])

In [22]:
describe(torch.index_select(x, dim=1, index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])


In [23]:
indices = torch.LongTensor([0,0])
describe(torch.index_select(x, dim=0, index=indices))

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [24]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])

In [25]:
row_indices

tensor([0, 1])

In [26]:
col_indices

tensor([0, 1])

In [27]:
describe(x[row_indices, col_indices])

타입: torch.LongTensor
크기: torch.Size([2])
값: 
tensor([0, 4])


In [30]:
x[[0,1]]

tensor([[0, 1, 2],
        [3, 4, 5]])

In [35]:
x[:, [0,1]]

tensor([[0, 1],
        [3, 4]])

In [36]:
describe(torch.cat([x,x],dim=0))

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [37]:
describe(torch.cat([x,x],dim=1))

타입: torch.LongTensor
크기: torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [38]:
describe(torch.stack([x,x]))

타입: torch.LongTensor
크기: torch.Size([2, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [39]:
x2 = torch.ones(3,2)
x2[:,1] += 1
describe(x2)

타입: torch.FloatTensor
크기: torch.Size([3, 2])
값: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [45]:
x1 = torch.arange(6).view(2,3).float()

In [46]:
x1.type()

'torch.FloatTensor'

In [47]:
describe(torch.mm(x1, x2))

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[ 3.,  6.],
        [12., 24.]])


In [48]:
x = torch.ones(2,2,requires_grad=True)
describe(x)
print(x.grad is None)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [49]:
print(torch.cuda.is_available())

False
