In [1]:
import torch
import numpy as np

In [4]:
def describe(x):
    print("타입: {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))

In [6]:
describe(torch.Tensor(2, 3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[8.4078e-45, 2.0000e+00, 7.9057e+24],
        [2.0005e+00, 1.3134e+22, 3.3585e-06]])


---

문제 1
<br> 2D 텐서를 만들고 차원 0 위치에 크기가 1인 차원을 추가하세요.

In [11]:
tensor1 = torch.Tensor([[1]])
describe(tensor1)
print('-'*10)

# solution ??????
a = torch.rand(3,3)
a.unsqueeze(0)
describe(a)

타입: torch.FloatTensor
크기: torch.Size([1, 1])
값: 
tensor([[1.]])
----------
타입: torch.FloatTensor
크기: torch.Size([3, 3])
값: 
tensor([[0.9681, 0.9861, 0.9957],
        [0.7283, 0.7639, 0.0286],
        [0.4692, 0.1051, 0.1487]])


문제 2
<br>이전 텐서에 추가한 차원을 삭제하세요.

In [14]:
# tensor1.squeeze(0)
# describe(tensor1)

# solution ???????
a.squeeze(0)
describe(a)

타입: torch.FloatTensor
크기: torch.Size([3, 3])
값: 
tensor([[0.9681, 0.9861, 0.9957],
        [0.7283, 0.7639, 0.0286],
        [0.4692, 0.1051, 0.1487]])


문제 3
<br> [3, 7) 범위를 갖는 5x3 크기의 랜덤한 텐서를 만드세요.

In [25]:
import random
tensor_list = list()
for _ in range(3):
    a = list()
    for __ in range(5):
        a.append(random.randint(3,6))
    tensor_list.append(a)
describe(torch.Tensor(tensor_list))

print('-'*10)

# solution
p3_sol = 3 + torch.rand(5,3) * (7-3)
describe(p3_sol)

타입: torch.FloatTensor
크기: torch.Size([3, 5])
값: 
tensor([[5., 4., 4., 6., 6.],
        [3., 6., 6., 5., 3.],
        [3., 4., 3., 5., 3.]])
----------
타입: torch.FloatTensor
크기: torch.Size([5, 3])
값: 
tensor([[4.7887, 5.9068, 3.3877],
        [3.1161, 3.2317, 3.9937],
        [6.4631, 5.7769, 5.0259],
        [5.0657, 6.1484, 5.5728],
        [3.9585, 6.4428, 4.4422]])


문제 4
<br> 정규 분포(평균=0, 표준편차=1)를 사용해 텐서를 만드세요.

In [27]:
describe(torch.randn(2,3)) # 이건 표준 정규분포로, 평균=0, 분산=1

print('-'*10)

# solution
describe(torch.rand(3,3).normal_())

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-1.0030,  0.1427, -0.8746],
        [ 0.4658, -1.0565, -1.6432]])
----------
타입: torch.FloatTensor
크기: torch.Size([3, 3])
값: 
tensor([[ 1.5052,  1.8867, -0.1453],
        [-2.8099,  0.7220,  0.1275],
        [ 1.5732,  0.5132, -0.8293]])


문제 5
<br> 텐서 torch.Tensor([1, 1, 1, 0, 1])에서 0이 아닌 원소의 인덱스를 추출하세요.

In [29]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

문제 6
<br> (3,1) 크기가 인 랜덤한 텐서를 만들고 네 벌을 복사해 쌓으세요.

In [34]:
base = torch.rand(3,1)
describe(base)
print('-'*10)
tmp = torch.cat([base, base], dim=1)
final = torch.cat([tmp, tmp], dim=1)
describe(final)
print('-'*10)
# solution
base.expand(3,4)

타입: torch.FloatTensor
크기: torch.Size([3, 1])
값: 
tensor([[0.3552],
        [0.8336],
        [0.5370]])
----------
타입: torch.FloatTensor
크기: torch.Size([3, 4])
값: 
tensor([[0.3552, 0.3552, 0.3552, 0.3552],
        [0.8336, 0.8336, 0.8336, 0.8336],
        [0.5370, 0.5370, 0.5370, 0.5370]])
----------


tensor([[0.3552, 0.3552, 0.3552, 0.3552],
        [0.8336, 0.8336, 0.8336, 0.8336],
        [0.5370, 0.5370, 0.5370, 0.5370]])

문제 7
<br> 두 개의 2차원 행렬(a=torch.rand(3,4,5), b=torch.rand(3,5,4))의 배치 행렬 곱셈(batch matrix-matrix product)을 계산하세요.

In [39]:
a=torch.rand(3,4,5)
b=torch.rand(3,5,4)

print(a.matmul(b)) # 둘다 맞는 듯,,,?!

# solution
torch.bmm(a, b)

tensor([[[1.1590, 0.8909, 0.8057, 1.0182],
         [1.5591, 1.1585, 1.0923, 1.1140],
         [1.4111, 1.0333, 1.2150, 1.1182],
         [1.8034, 1.1298, 0.7946, 1.3338]],

        [[1.9227, 1.4499, 2.2779, 1.9620],
         [1.3621, 1.5984, 1.2965, 1.4332],
         [1.5571, 1.2287, 1.7681, 1.4428],
         [1.3773, 1.2335, 1.7856, 1.6191]],

        [[1.1194, 2.0144, 0.9377, 1.4542],
         [0.8915, 1.8976, 0.9701, 1.4235],
         [1.5585, 3.0017, 1.2816, 2.3413],
         [0.7374, 1.5348, 0.5050, 1.3821]]])


tensor([[[1.1590, 0.8909, 0.8057, 1.0182],
         [1.5591, 1.1585, 1.0923, 1.1140],
         [1.4111, 1.0333, 1.2150, 1.1182],
         [1.8034, 1.1298, 0.7946, 1.3338]],

        [[1.9227, 1.4499, 2.2779, 1.9620],
         [1.3621, 1.5984, 1.2965, 1.4332],
         [1.5571, 1.2287, 1.7681, 1.4428],
         [1.3773, 1.2335, 1.7856, 1.6191]],

        [[1.1194, 2.0144, 0.9377, 1.4542],
         [0.8915, 1.8976, 0.9701, 1.4235],
         [1.5585, 3.0017, 1.2816, 2.3413],
         [0.7374, 1.5348, 0.5050, 1.3821]]])

문제 8
<br> 3차원 행렬(a=torch.rand(3,4,5))과 2차원 행렬(b=torch.rand(5,4))의 배치 행렬 곱셈을 계산하세요.

In [43]:
a=torch.rand(3,4,5)
b=torch.rand(5,4)

print(a.matmul(b)) # 7번 문제와 달리, 배치 차원을 맞추어 줘야함?... 일단 이것도 맞는가본디

# solution
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size())) ###???

tensor([[[0.9044, 1.7234, 1.1598, 1.7060],
         [1.7780, 1.8362, 1.5359, 1.3553],
         [1.6616, 2.5525, 1.8752, 2.3692],
         [1.1294, 1.8752, 1.4342, 1.7308]],

        [[0.9315, 1.7528, 1.0709, 1.7663],
         [1.2363, 1.9329, 1.4184, 1.8183],
         [1.7008, 2.5542, 1.8605, 2.3219],
         [0.9273, 1.5969, 1.0916, 1.5303]],

        [[0.5080, 1.0863, 0.7811, 1.2178],
         [1.2209, 1.7996, 1.5006, 1.6768],
         [1.7022, 2.1171, 1.6782, 1.7233],
         [1.5685, 2.1213, 1.6569, 1.8963]]])


tensor([[[0.9044, 1.7234, 1.1598, 1.7060],
         [1.7780, 1.8362, 1.5359, 1.3553],
         [1.6616, 2.5525, 1.8752, 2.3692],
         [1.1294, 1.8752, 1.4342, 1.7308]],

        [[0.9315, 1.7528, 1.0709, 1.7663],
         [1.2363, 1.9329, 1.4184, 1.8183],
         [1.7008, 2.5542, 1.8605, 2.3219],
         [0.9273, 1.5969, 1.0916, 1.5303]],

        [[0.5080, 1.0863, 0.7811, 1.2178],
         [1.2209, 1.7996, 1.5006, 1.6768],
         [1.7022, 2.1171, 1.6782, 1.7233],
         [1.5685, 2.1213, 1.6569, 1.8963]]])